 # docker run -d --name ethereum-node -v /Users/alice/ethereum:/root  \
 # -p 8545:8545 -p 30303:30303 \
 # ethereum/client-go --fast --cache=512 --testnet

ethereum:
   image: ethereum/client-go
   container_name: stellar-ethereum
   command: --fast --cache=512 --testnet --rpcaddr 0.0.0.0
   volumes:
     - /home/steve/ethereum-test:/root
   restart: unless-stopped
   ports:
     - 8545:8545/tcp
     - 30303:30303/tcp
